//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicActaObra
    {
        public int idLicActaObra { get; set; }
        public Nullable<int> idObra { get; set; }
        public string actaEncabezado { get; set; }
        public string actaFormal { get; set; }
        public string actaOferta { get; set; }
        public string actaCierre { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<int> idUsuarioAlta { get; set; }
        public Nullable<System.DateTime> fechaModif { get; set; }
        public Nullable<int> idUsuarioModif { get; set; }
    }
}
