//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicArchivoEmpresa
    {
        public int idArchivo { get; set; }
        public Nullable<int> idObra { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public Nullable<int> idRequisito { get; set; }
        public string nombreArchivo { get; set; }
        public string ruta { get; set; }
        public string clave { get; set; }
        public string nombreArchivoEnc { get; set; }
        public string rutaVirtual { get; set; }
        public Nullable<int> nroSobre { get; set; }
        public Nullable<int> idEstadoArchivo { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string tipoArchivo { get; set; }
    }
}
