//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicArchivoObra
    {
        public int idLicArchivoObra { get; set; }
        public Nullable<int> idObra { get; set; }
        public string nombreArchivo { get; set; }
        public string rutaArchivo { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
