//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicActaGenerica
    {
        public int idLicActaGenerica { get; set; }
        public string actaEncabezado { get; set; }
        public string actaFormal { get; set; }
        public string actaOferta { get; set; }
        public string actaCierre { get; set; }
    }
}
