//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicDocGeneral
    {
        public int idLicDocGeneral { get; set; }
        public Nullable<int> esPadre { get; set; }
        public string nombre { get; set; }
        public Nullable<int> activo { get; set; }
        public Nullable<int> idPadre { get; set; }
    }
}
