//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicEmpresaObra
    {
        public int idLicEmpresaObra { get; set; }
        public int idObra { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public Nullable<int> esFavorito { get; set; }
    }
}
