//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicOferta
    {
        public int idLicOferta { get; set; }
        public Nullable<int> idObra { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public Nullable<int> fechaOferta { get; set; }
        public Nullable<decimal> montoOferta { get; set; }
        public Nullable<int> idEstadoOferta { get; set; }
    }
}
