//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicProyectoFecha
    {
        public int idLicProyectoFecha { get; set; }
        public Nullable<int> idProyecto { get; set; }
        public Nullable<System.DateTime> fechaPublicacion { get; set; }
        public Nullable<System.DateTime> fechaCierre { get; set; }
        public Nullable<System.DateTime> fechaApertura { get; set; }
        public string horaApertura { get; set; }
    }
}
