//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicProyecto
    {
        public int idLicProyecto { get; set; }
        public int idProyecto { get; set; }
        public Nullable<int> moneda { get; set; }
        public string urlPliego { get; set; }
        public string mailConsulta { get; set; }
        public Nullable<System.DateTime> limiteConsulta { get; set; }
        public string domicilioPresentacion { get; set; }
        public string domicilioApertura { get; set; }
        public Nullable<System.DateTime> fechaVisita { get; set; }
        public string lugarVisita { get; set; }
        public Nullable<System.DateTime> fechaCierre { get; set; }
        public Nullable<int> idUsuarioModif { get; set; }
        public Nullable<System.DateTime> fechaModif { get; set; }
    }
}
