//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class PryEstadoEtapa
    {
        public int Id { get; set; }
        public Nullable<int> PryStage_Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Order { get; set; }
        public int PryEtapa_Id { get; set; }
    }
}
