//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class PryProyectoDimension
    {
        public int idPryProyectoDimension { get; set; }
        public string nombrePryProyectoDimension { get; set; }
        public int ordenPryProyectoDimension { get; set; }
    }
}
