//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class PryProyecto
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Expediente { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaDeAlta { get; set; }
        public int PryFuenteFinanciamiento_Id { get; set; }
        public Nullable<int> TipoDeContratacion_Id { get; set; }
        public string Dirección { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public Nullable<int> GrlZone_Id { get; set; }
        public Nullable<int> GrlDepartament_Id { get; set; }
        public Nullable<int> PryOrganismoEjecutor_Id { get; set; }
        public Nullable<int> PryEmpresa_Id { get; set; }
        public bool Eliminado { get; set; }
        public Nullable<int> GrlTypeState_Id { get; set; }
        public Nullable<int> Dias { get; set; }
        public Nullable<bool> EsAlteracion { get; set; }
        public Nullable<int> IdProyectoPadre { get; set; }
        public Nullable<int> Plazo { get; set; }
        public Nullable<decimal> cantIntervenciones { get; set; }
        public Nullable<int> usuCarga { get; set; }
        public Nullable<int> oficinaCarga { get; set; }
        public Nullable<int> tipoAlteracion_Id { get; set; }
        public byte[] File { get; set; }
        public Nullable<int> usuModificacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<int> tipoObra_Id { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> tipoUnidad_Id { get; set; }
        public Nullable<int> prioridad_Type_Id { get; set; }
        public Nullable<int> Subcategoria_Id { get; set; }
        public string codigoObra { get; set; }
        public string normaContrato { get; set; }
        public string normaAdjudicacion { get; set; }
        public string decretoContrato { get; set; }
        public string decretoAdjudicacion { get; set; }
        public Nullable<int> ufiOrgano_Id { get; set; }
        public Nullable<int> PryAlcance_Id { get; set; }
        public Nullable<int> PryProyectoCategoria_Id { get; set; }
        public Nullable<int> PryODS_Id { get; set; }
        public Nullable<int> PryFinanciacion_Id { get; set; }
        public Nullable<int> PryPreguntas_Id { get; set; }
        public string CaratulaExpediente { get; set; }
        public string funcionario { get; set; }
        public string cargoFuncionario { get; set; }
        public string responsableTec { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string financiamiento { get; set; }
        public string fechaNormaAdjudicacion { get; set; }
        public string fechaNormaContrato { get; set; }
        public string manoObra { get; set; }
        public Nullable<int> tipoMonedaMontoContratado { get; set; }
        public Nullable<int> PryProyectoDimension_Id { get; set; }
        public Nullable<int> ufiOrganoReceptor_Id { get; set; }
        public string duenoTerreno { get; set; }
        public string nomenCatastral { get; set; }
        public Nullable<System.DateTime> fechaMonto { get; set; }
        public Nullable<System.DateTime> fechaRecepcion { get; set; }
        public string numeroLicitacion { get; set; }
        public Nullable<int> idAdminGeren { get; set; }
        public string telAdminGeren { get; set; }
        public string emailAdminGeren { get; set; }
        public Nullable<int> idInspector { get; set; }
        public Nullable<int> idPryProyectoTipoCertificacion { get; set; }
    
        public virtual PryProyectoTipoCertificacion PryProyectoTipoCertificacion { get; set; }
    }
}
