//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class PryProyectoEtapa
    {
        public int idPryProyectoEtapa { get; set; }
        public string namePryProyectoEtapa { get; set; }
        public string descriptionPryProyectoEtapa { get; set; }
        public int ordenPryProyectoEtapa { get; set; }
    }
}
