//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class PryProyectoCategoria
    {
        public int IdPryProyectoCategoria { get; set; }
        public string nombrePryProyectoCategoria { get; set; }
        public int ordenPryProyectoCategoria { get; set; }
        public Nullable<int> subOrdenPryProyectoCategoria { get; set; }
        public Nullable<int> pryProyectoDimension_Id { get; set; }
    }
}
