//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class PryProyectoExpediente
    {
        public int id { get; set; }
        public string nroExpediente { get; set; }
        public string caratulaExpediente { get; set; }
        public int idPryTipoLicitacion { get; set; }
        public int idPryProyecto { get; set; }
    }
}
