//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class PryProyectoPlanificacion
    {
        public int Id { get; set; }
        public Nullable<decimal> MontoContratado { get; set; }
        public Nullable<decimal> MontoOficial { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<decimal> CoeficienteAnticipio { get; set; }
        public int PryProyecto_Id { get; set; }
        public bool Eliminado { get; set; }
        public Nullable<decimal> MontoAlterado { get; set; }
        public Nullable<System.DateTime> FechaAlterada { get; set; }
        public Nullable<int> AnhoInicioObra { get; set; }
        public Nullable<int> AnhoInaguracionObra { get; set; }
        public Nullable<int> AnhoRecepcionObra { get; set; }
    }
}
