//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class PryProyectoEspecialidad
    {
        public int id { get; set; }
        public int idPryEspecialidad { get; set; }
        public int idPryProyecto { get; set; }
        public Nullable<int> porcentaje100to400 { get; set; }
        public Nullable<int> porcentaje500 { get; set; }
    }
}
