//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class PryProyectoEstado
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaModificación { get; set; }
        public Nullable<int> PryProyecto_Id { get; set; }
        public Nullable<int> GrlTypeState_Id { get; set; }
    }
}
