//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegOffice
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int State_Type_Id { get; set; }
        public string Code { get; set; }
        public string Office { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> Nivel { get; set; }
        public sbyte Eliminado { get; set; }
        public Nullable<int> idOfficePadre { get; set; }
    }
}
