//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegPassword
    {
        public int Id { get; set; }
        public int SegUser_Id { get; set; }
        public string Hash { get; set; }
        public int Secuence { get; set; }
        public System.DateTime Date { get; set; }
    }
}
