//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegUserTitulo
    {
        public int idSegUserTitulo { get; set; }
        public int idUser { get; set; }
        public int idTitulo { get; set; }
        public string genero { get; set; }
    }
}
