//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SubEspecialidades
    {
        public int id { get; set; }
        public Nullable<int> Especialidad { get; set; }
        public string CodSubEsp { get; set; }
        public string SubEspecialidad { get; set; }
        public string Descripcion { get; set; }
    }
}
